<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SAMEER" failures="3" tests="5" name="Test" time="23.609" errors="0" timestamp="2024-10-15T12:48:55 IST">
  <testcase classname="testCases.EC003_LoginDDT" name="verify_loginDDT" time="3.422"/>
  <testcase classname="testCases.EC003_LoginDDT" name="verify_loginDDT" time="0.695">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.EC003_LoginDDT.verify_loginDDT(EC003_LoginDDT.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.EC003_LoginDDT" name="verify_loginDDT" time="1.083">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.EC003_LoginDDT.verify_loginDDT(EC003_LoginDDT.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.EC003_LoginDDT" name="verify_loginDDT" time="1.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.EC003_LoginDDT.verify_loginDDT(EC003_LoginDDT.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.EC003_LoginDDT" name="verify_loginDDT" time="3.46"/>
</testsuite> <!-- Test -->
